# -*- coding: utf-8 -*-
"""광진구 어린이 보호구역 위치도.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4U3zDZrWaB6HxC_8so7ON8Q_NCswulc
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/공모전/광진구/어린이보호구역 위치도.csv', encoding='euc-kr')
df

df.info()

#결측치 확인
df.isnull().sum()

#광진구만 추출
df = df[df['구']=='광진구']
df

#칼럼 제거
df.drop(['아이디','geometry','관리번호','관할경찰서','동','구'],inplace=True,axis=1)
df

df.rename(columns={'x좌표':'경도', 'y좌표':'위도'},inplace=True)

df = df[['시설명', '시설구분', '주소', '위도','경도']]
df

df.to_csv('광진구 어린이 보호구역 좌표.csv',encoding='utf-8-sig',index = False)