# -*- coding: utf-8 -*-
"""어린이집 현황.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ok2KqTzHDw8MR5nPWhpCAlzOTIpZ4u_K
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/공모전/광진구/서울시 광진구 유치원 일반현황.csv', encoding='euc-kr')
df

df.info()

#필요한 column만 추출
df =df.loc[:,['유치원명','주소','유아수']]
df

#데이터프레임 주소값 추출
address = df['주소']
address

# 주소 데이터 도로명까지만 추출되도록 처리
for i in range(len(address)):
    a = address[i].split(' ')
    address[i] = " ".join(a[0:4])
print(address)



####### 도로명주소 위도 경도 값으로 바꿔주기 ########
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

# 위도, 경도 반환하는 함수
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

#####주소를 위,경도 값으로 변환하기 #####
latitude = []
longitude =[]

for i in address:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

#####Dataframe만들기######
address_df = pd.DataFrame({'유치원명': df['유치원명'],'주소':df['주소'],'유아 수':df['유아수'],'위도':latitude,'경도':longitude})
address_df

#변환 안 된 주소값 확인
df[address_df['위도']==0]

#변환 안 된 주소 추가 변환 처리
address_df.loc[address_df['유치원명']=='자양하나유치원', '위도'] = 37.5387999
address_df.loc[address_df['유치원명']=='자양하나유치원', '경도'] = 127.078572

address_df.loc[address_df['유치원명']=='광장유치원', '위도'] = 37.5484381
address_df.loc[address_df['유치원명']=='광장유치원', '경도'] = 127.105198

address_df

#df저장
address_df.to_csv('광진구 어린이집 현황 좌표화.csv',encoding='utf-8-sig',index = False)